image:
  repository: nguyennamthai/java-heap-dump-operator
  pullPolicy: Always
  tag: "1"

name: gc-operator
labels:
  app: gc-operator
controllerPort: 9000
s3DumpLocation:
  bucket: https://hivecpq-dev-artifacts.s3.eu-central-1.amazonaws.com
  prefix: dump

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
