apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels: {{ toYaml .Values.labels | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{ toYaml .Values.labels | nindent 6 }}
  template:
    metadata:
      labels: {{ toYaml .Values.labels | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.name }}
      containers:
        - name: operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SERVICE_NAME
              value: {{ .Values.name }}
            - name: CONTROLLER_PORT
              value: {{ .Values.controllerPort }}
            - name: S3_DUMP_BUCKET
              value: {{ .Values.s3DumpLocation.bucket }}
            - name: S3_DUMP_PREFIX
              value: {{ .Values.s3DumpLocation.prefix }}
          ports:
            - containerPort: {{ .Values.controllerPort }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
