apiVersion: apps/v1
kind: Deployment
metadata:
  name: gc-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app: gc-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gc-operator
  template:
    metadata:
      labels:
        app: gc-operator
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SERVICE_NAME
              value: {{ .Values.serviceName }}
            - name: CONTROLLER_PORT
              value: {{ .Values.controllerPort }}
          ports:
            - containerPort: {{ .Values.controllerPort }}
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
