apiVersion: apps/v1
kind: Deployment
metadata:
  name: gc-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app: gc-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gc-operator
  template:
    metadata:
      labels:
        app: gc-operator
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CONTROLLER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
